<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Without.Systems.RulesEspresso</RootNamespace>
        <AssemblyName>Without.Systems.RulesEspresso.Library</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DynamicExpresso.Core" Version="2.19.6" />
        <PackageReference Include="NJsonSchema" Version="11.6.1" />
        <PackageReference Include="OutSystems.ExternalLibraries.SDK" Version="1.7.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\Rules.png" />
      <EmbeddedResource Include="Resources\Rules.png" />
    </ItemGroup>

</Project>
